name: sprint daily (manual)

on:
  workflow_dispatch:
    inputs:

jobs:
  generate_burndown_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Generate burndown chart
        uses: ./
        with:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DB_BACKLOG: ecb201f856f0467d9b30be50a212a895
          NOTION_DB_SPRINT_SUMMARY: 0d3b0624eeda43b4bf6799df4ece2c8a
          NOTION_DB_DAILY_SUMMARY: 0c694147671740ad8ee9879ecd4fc53b
          NOTION_PROPERTY_SPRINT: Sprint
          NOTION_PROPERTY_ESTIMATE: Estimate
          NOTION_PROPERTY_PATTERN_STATUS_EXCLUDE: Completed|Released
      - name: Commit burndown chart
        run: |
          git config --local user.email "cestivan@163.com"
          git config --local user.name "Ivan"
          git add ./out
          git commit -m "run: upload new burndown chart"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
